/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/icon/Icon.vue')['default']
    NutEllipsis: typeof import('@nutui/nutui-taro')['Ellipsis']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    TimeAgo: typeof import('./src/components/TimeAgo.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo/UserInfo.vue')['default']
  }
}
