// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Fans: typeof import('./src/components/fans.vue')['default']
    More: typeof import('./src/components/more.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    Time: typeof import('./src/components/time.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
